---

variables:
  SAST_EXCLUDED_PATHS: '_venv, docs/howto/_venv'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - pack
  - deploy
  - release

image: postgres:13

include:
  - local: ci/doc.yml
  ## Default PG version is ALWAYS built and tested
  - local: ci/build_and_test_pgver.yml
    inputs:
      always: 'yes'   # this is a string not a boolean
      pgver: pg13
  ## Other PG versions are built and tested only on the `main` branch
  - local: ci/build_and_test_pgver.yml
    inputs:
      pgver: pg12
  - local: ci/build_and_test_pgver.yml
    inputs:
      pgver: pg14
  - local: ci/build_and_test_pgver.yml
    inputs:
      pgver: pg15
  - local: ci/build_and_test_pgver.yml
    inputs:
      pgver: pg16
  ## automatic SAST from Gitlab.com
  - template: Security/SAST.gitlab-ci.yml



